import type { EmotionLesson } from "./emotionLessons";

type Practice = EmotionLesson["practice"];
type Field = NonNullable<Practice["fields"]>[number];

const text = (id: string, label: string, placeholder?: string): Field => ({
  id, label, type: "text", placeholder, required: true,
});
const area = (id: string, label: string, placeholder?: string): Field => ({
  id, label, type: "textarea", placeholder, required: true,
});
const scale = (id: string, label: string): Field => ({
  id, label, type: "scale", required: true,
});

export const IDENTITY_PRACTICE_COPY: Practice[] = [
  {
    title: "Vysyp svoje role na stůl.",
    why: "Uvidíš, kolik prostoru zabírají jednotlivé funkce a co v mapě zůstává i mimo ně.",
    whyBullets: ["Napiš role, které během týdne skutečně žiješ.", "U každé odhadni, kolik pozornosti zabírá.", "Přidej jednu část sebe, která není funkcí pro druhé."],
    steps: ["Které role nosím nejčastěji?", "Která dnes zabírá nejvíc prostoru?", "Co je mi vlastní, i když tuto roli na chvíli odložím?"],
    prompt: "Co se objeví, když vedle rolí nechám místo i pro člověka?",
    fields: [area("roles", "Moje současné role"), text("largest", "Role s největším podílem prostoru"), area("beyond", "Co ve mně zůstává mimo role")],
  },
  {
    title: "Naplánuj půlhodinu bez dokazování.",
    why: "Krátce vyzkoušíš, jaké je být se sebou bez výsledku, užitečnosti a odškrtnutého úkolu.",
    whyBullets: ["Vyber třicet minut, které nejsou odměnou po výkonu.", "Nedělej z nich další projekt se správným výsledkem.", "Zachyť věty, které tě táhnou zpět k užitečnosti."],
    steps: ["Kdy proběhne moje půlhodina bez výkonu?", "Co se ve mně ozvalo, když jsem nic nedokazoval?", "Co o mně zůstalo pravdivé i bez výsledku?"],
    prompt: "Jaké je být chvíli člověkem, ne úkolem?",
    fields: [text("when", "Čas pro půlhodinu bez dokazování"), area("voices", "Co se ve mně ozývalo"), area("remains", "Co o mně zůstává pravdivé")],
  },
  {
    title: "Postav jednu starou větu před soud důkazů.",
    why: "Příběh o sobě nepopřeš. Ověříš ale, zda skutečně obsahuje celou dostupnou zkušenost.",
    whyBullets: ["Zapiš obvyklou větu přesně, bez změkčování.", "Najdi jeden důkaz pro ni a dva, které se do ní nevejdou.", "Napiš přesnější verdikt místo opačného extrému."],
    steps: ["Jaká věta o mně zní jako fakt?", "Které dvě zkušenosti jí odporují?", "Jak zní přesnější a otevřenější popis?"],
    prompt: "Jaký rozsudek obstojí před všemi dostupnými důkazy?",
    fields: [text("oldStory", "Stará věta o sobě"), area("support", "Zkušenost, která ji podporuje"), area("exceptions", "Dvě důležité výjimky"), area("newStory", "Přesnější pracovní věta")],
  },
  {
    title: "Otevři jednu nálepku a podívej se dovnitř.",
    why: "Jedno slovo rozložíš na situace, výjimky a možnost, kterou předem zavírá.",
    whyBullets: ["Vyber nálepku, kterou o sobě často používáš.", "Urči, kde sedí a kde ne.", "Navrhni jeden malý pokus mimo její hranice."],
    steps: ["Kdy mě nálepka popisuje docela přesně?", "Kdy se do ní nevejdu?", "Co bych jednou zkusil, kdyby nerozhodovala předem?"],
    prompt: "Co se změní, když nálepku použiju jako popis, ne jako zákaz?",
    fields: [text("label", "Moje nálepka"), area("fits", "Kde sedí"), area("doesNotFit", "Kde nesedí"), area("experiment", "Jeden bezpečný pokus mimo ni")],
  },
  {
    title: "Sestav si sbírku tří skutečných důkazů.",
    why: "Kvalitu nebudeš dokazovat přáním, ale konkrétními okamžiky, které už se opravdu staly.",
    whyBullets: ["Vyber jednu kvalitu, o které pochybuješ.", "Najdi tři malé situace z různých období.", "U každé popiš čin, ne vlastní hodnocení."],
    steps: ["Kterou kvalitu hledám?", "Které tři činy ji už ukázaly?", "Co mají tyto situace společného?"],
    prompt: "Jakou kvalitu už dokládá moje vlastní zkušenost?",
    fields: [text("quality", "Hledaná kvalita"), area("evidence", "Tři konkrétní důkazy"), area("conditions", "Co jim pomohlo vzniknout")],
  },
  {
    title: "Přepiš jeden automatický hlasovací lístek.",
    why: "Běžná volba dnes posílí buď starý příběh, nebo malou alternativu, kterou si chceš vyzkoušet.",
    whyBullets: ["Najdi volbu, kterou děláš skoro bez přemýšlení.", "Pojmenuj příběh, který tím znovu potvrzuješ.", "Navrhni jeden odlišný hlas pro příští situaci."],
    steps: ["Jaká moje volba se často opakuje?", "Jakou větu o mně tím posiluje?", "Jaký malý čin by přidal jiný důkaz?"],
    prompt: "Pro který příběh o sobě chci příště hlasovat?",
    fields: [area("automatic", "Opakující se automatická volba"), text("story", "Příběh, který posiluje"), area("newVote", "Jiný malý čin")],
  },
  {
    title: "Vytvoř čtyřvrstvou mapu dnešního já.",
    why: "Oddělíš role, staré příběhy, doložené kvality a chování, které právě opakuješ.",
    whyBullets: ["Piš stručně a konkrétně.", "Nenech jednu vrstvu vysvětlovat všechny ostatní.", "Zakroužkuj místo, které chceš v dalším týdnu pozorovat."],
    steps: ["Jaké role dnes žiju?", "Jaké příběhy a skutečné kvality si nesu?", "Které opakované chování chci sledovat dál?"],
    prompt: "Jak vypadá moje dnešní mapa bez jediné konečné nálepky?",
    fields: [area("roles", "Role"), area("stories", "Staré věty a příběhy"), area("qualities", "Kvality doložené činy"), area("patterns", "Opakované chování"), text("focus", "Jedno místo pro další týden")],
  },
  {
    title: "Vyměň portrét hotového já za šipku.",
    why: "Místo vzdálené dokonalé postavy si zvolíš směr, ve kterém lze udělat krok ještě s dnešní nejistotou.",
    whyBullets: ["Zachyť ideální verzi sebe, na kterou čekáš.", "Přelož ji do jedné kvality směru.", "Najdi krok, který nevyžaduje hotovou proměnu."],
    steps: ["Na jaký pocit nebo verzi sebe čekám?", "Jaký směr se pod tím skrývá?", "Co můžu udělat i s tím, co dnes cítím?"],
    prompt: "Kam ukazuje moje šipka, i když ještě nejsem v cíli?",
    fields: [area("ideal", "Hotová verze, na kterou čekám"), text("direction", "Zvolený směr"), area("step", "Krok možný už dnes")],
  },
  {
    title: "Přidej svému cíli způsob chůze.",
    why: "Výsledek doplníš o kvalitu, kterou chceš cestou přinášet sobě i lidem kolem.",
    whyBullets: ["Vyber jeden skutečný současný cíl.", "Pojmenuj způsob, kterým ho nechceš naplňovat.", "Zvol dvě kvality pro příští konkrétní situaci."],
    steps: ["Čeho chci dosáhnout?", "Jakým člověkem při tom nechci být?", "Které dvě kvality chci přinést do dalšího kroku?"],
    prompt: "Jak chci jít, ne jen kam chci dojít?",
    fields: [area("goal", "Můj konkrétní cíl"), area("notThisWay", "Způsob, který nechci opakovat"), text("qualities", "Dvě zvolené kvality"), area("scene", "Kde je použiju nejdřív")],
  },
  {
    title: "Nacvič jednu větu pro chvíli nesouhlasu.",
    why: "Vztahová identita dostane konkrétní podobu právě tam, kde se obvykle stáhneš nebo začneš tlačit.",
    whyBullets: ["Vyber reálné, ale bezpečné téma.", "Spoj vlastní zkušenost s prostorem pro druhého.", "Připrav také větu pro návrat po chybě."],
    steps: ["Co potřebuju říct za sebe?", "Jak dám najevo, že druhý může situaci vidět jinak?", "Jak se vrátím, pokud rozhovor nezvládnu podle představ?"],
    prompt: "Jak chci znít ve vztahu, když se neshodneme?",
    fields: [area("topic", "Konkrétní téma"), area("mySentence", "Moje jasná věta"), area("space", "Věta, která nechá prostor druhému"), area("repair", "Věta pro případný návrat")],
  },
  {
    title: "Odděl pracovní chybu od celého člověka.",
    why: "Uděláš přesné vyhodnocení výkonu bez toho, aby jeden výsledek spolkl všechny ostatní části identity.",
    whyBullets: ["Vyber jednu chybu nebo slabší výsledek.", "Popiš odpovědnost a poučení konkrétně.", "Doplň tři části sebe, o kterých tato práce nerozhoduje."],
    steps: ["Co se v práci skutečně nepovedlo?", "Co opravím nebo se naučím?", "Co tato situace nevypovídá o celé mé osobě?"],
    prompt: "Jak vypadá odpovědnost bez rozsudku nad sebou?",
    fields: [area("error", "Přesný popis chyby nebo výsledku"), area("repair", "Oprava a poučení"), area("notVerdict", "Co z toho nelze vyvozovat o celém mně")],
  },
  {
    title: "Dej péči o sebe do kalendáře před kolaps.",
    why: "Vybereš malý čin, který reaguje na kapacitu dřív, než se odpočinek stane vynucenou opravou.",
    whyBullets: ["Najdi první běžný signál klesající kapacity.", "Zvol péči, která zabere nejvýš třicet minut.", "Urči čas, který není podmíněný dokončením všeho."],
    steps: ["Jak poznám první pokles kapacity?", "Jaký malý čin péče odpovídá tomuto signálu?", "Kdy ho provedu bez čekání na vyčerpání?"],
    prompt: "Jak se dnes zachová člověk, který bere svoji kapacitu vážně?",
    fields: [text("signal", "Můj časný signál"), area("care", "Konkrétní čin péče"), text("when", "Přesný čas nebo situace"), scale("realistic", "Jak realistický je plán od 1 do 5")],
  },
  {
    title: "Vyrob jeden důkaz ještě před koncem dne.",
    why: "Nová věta o sobě získá malý čin, který lze skutečně vidět, slyšet nebo dokončit.",
    whyBullets: ["Vyber směr, který je dnes živý.", "Zmenši čin tak, aby šel udělat do večera.", "Po provedení zapiš faktický výsledek."],
    steps: ["Jakou větu o svém směru chci podpořit?", "Jaký nejmenší čin ji dnes doloží?", "Co se skutečně stalo po jeho provedení?"],
    prompt: "Jaký důkaz můžu vytvořit dřív, než budu mít pocit, že jsem připravený?",
    fields: [text("identity", "Věta o zvoleném směru"), area("act", "Nejmenší dnešní čin"), area("result", "Skutečný výsledek")],
  },
  {
    title: "Vytvoř trojpanel budoucího já.",
    why: "Budoucí obraz rozdělíš do vztahů, práce a péče o sebe a ke každému přidáš jeden viditelný důkaz.",
    whyBullets: ["Nevytvářej bezchybnou postavu.", "V každém panelu zvol jednu kvalitu.", "Každou kvalitu spoj s obyčejným chováním."],
    steps: ["Jakou kvalitu chci žít ve vztazích?", "Jakou kvalitu chci žít v práci?", "Jakou kvalitu chci žít v péči o sebe?"],
    prompt: "Jak bude můj budoucí směr vidět ve třech částech života?",
    fields: [area("relations", "Vztahy: kvalita a jeden čin"), area("work", "Práce: kvalita a jeden čin"), area("care", "Péče o sebe: kvalita a jeden čin"), text("first", "Který důkaz vytvořím jako první")],
  },
  {
    title: "Natoč v hlavě devadesátisekundový film obyčejného dne.",
    why: "Abstraktní vizi přeložíš do konkrétních scén, rytmu, lidí a pocitu z běžného života.",
    whyBullets: ["Nezačínej vrcholem ani dovolenou.", "Projdi ráno, pracovní část a večer.", "Všimni si detailu, který se nejvíc liší od dneška."],
    steps: ["Jak vypadá první hodina tohoto dne?", "Jak pracuju a s kým jsem během dne v kontaktu?", "Jak vypadá večer a s jakým pocitem usínám?"],
    prompt: "Který detail obyčejného dne ukazuje, že je tato vize opravdu moje?",
    fields: [area("morning", "Ráno"), area("day", "Práce, lidé a rytmus dne"), area("evening", "Večer"), area("difference", "Nejdůležitější rozdíl oproti dnešku")],
  },
  {
    title: "Napiš vztahovou vizi pouze ze své poloviny hřiště.",
    why: "Oddělíš to, co chceš do vztahu přinášet, od toho, co musí vzniknout společně nebo závisí na druhém.",
    whyBullets: ["Zvol jeden důležitý vztah nebo typ vztahu.", "Piš jen vlastní jednání, hranice a způsob návratu.", "Zvlášť označ, co nemůžeš vytvořit sám."],
    steps: ["Jak chci mluvit a naslouchat já?", "Jak chci zacházet s hranicí a chybou?", "Co potřebuji od druhého, ale nemohu to řídit?"],
    prompt: "Co je na mojí polovině vztahového hřiště?",
    fields: [area("bring", "Co chci přinášet já"), area("boundary", "Jak chci zacházet s hranicí a konfliktem"), area("shared", "Co musí vzniknout společně"), area("outside", "Co nemůžu ovládat")],
  },
  {
    title: "Sestav pracovní vizi ze čtyř stavebních kostek.",
    why: "Pozice a příjem doplníš o činnost, přínos, podmínky a cenu, kterou jsi ochoten přijmout.",
    whyBullets: ["Nezačínej názvem vysněné pozice.", "Popiš, čemu chceš dávat většinu energie.", "Přidej podmínky nutné pro dlouhodobou udržitelnost."],
    steps: ["Jaké problémy nebo činnosti mě mají zaměstnávat?", "Komu nebo čemu chci přispívat?", "Jaké tempo, vztahy a podmínky potřebuji?"],
    prompt: "Jaká práce dává smysl nejen z dálky, ale i v běžném týdnu?",
    fields: [area("activities", "Činnosti a problémy"), area("contribution", "Přínos"), area("conditions", "Tempo, lidé a podmínky"), area("needs", "Materiální potřeby a hranice")],
  },
  {
    title: "Udělej malý redesign prostředí.",
    why: "Jednu žádoucí volbu usnadníš a jeden starý automat uděláš o trochu méně dostupný.",
    whyBullets: ["Vyber jediné chování pro příští týden.", "Odstraň jeden rušivý podnět.", "Přidej jednu viditelnou nebo časovou oporu."],
    steps: ["Které chování chci prostředím podpořit?", "Co mu dnes pravidelně překáží?", "Jakou jednu překážku uberu a jakou oporu přidám?"],
    prompt: "Co může moje prostředí udělat za mě dřív, než zapojím vůli?",
    fields: [area("behavior", "Chování, které chci podpořit"), area("friction", "Současná překážka"), area("remove", "Co odstraním nebo ztížím"), area("support", "Co připravím nebo zviditelním")],
  },
  {
    title: "Najdi dominovou kostku mezi dneškem a vizí.",
    why: "Z mnoha rozdílů vybereš jeden, jehož posun může uvolnit prostor ve více oblastech.",
    whyBullets: ["Sepiš nejvýš pět rozdílů oproti vizi.", "U každého označ oblasti, které ovlivňuje.", "Vyber změnu s velkým dopadem a realistickým prvním krokem."],
    steps: ["Které rozdíly mezi dneškem a vizí vidím?", "Který z nich zasahuje více částí života?", "Jaký nejmenší posun této kostky je možný?"],
    prompt: "Která jedna změna může otevřít další možnosti?",
    fields: [area("gaps", "Nejvýš pět rozdílů"), text("domino", "Vybraná dominová kostka"), area("impact", "Co dalšího ovlivňuje"), area("move", "Nejmenší první posun")],
  },
  {
    title: "Postav sedmidenní most o třech prknech.",
    why: "Vizi spojíš s realitou pomocí jasného okamžiku, konkrétního činu a připravené opory.",
    whyBullets: ["Vyber jen jednu mezeru z předchozího dne.", "Urči přesný čas nebo spouštěč.", "Připrav plán pro nejpravděpodobnější překážku."],
    steps: ["Kdy přesně na most vstoupím?", "Co je moje jediné pozorovatelné jednání?", "Co udělám, když přijde známá překážka?"],
    prompt: "Jak vypadají tři prkna mezi dneškem a jedním krokem vize?",
    fields: [text("when", "Kdy nebo při čem začnu"), area("action", "Jeden konkrétní čin"), area("obstacle", "Nejpravděpodobnější překážka"), area("ifThen", "Když překážka přijde, udělám…"), area("observe", "Co po sedmi dnech vyhodnotím")],
  },
  {
    title: "Slož kompas z pěti krátkých vět.",
    why: "Místo dlouhého shrnutí vytvoříš rychlou mapu, ke které se dá vrátit v jedné skutečné situaci.",
    whyBullets: ["Každou vrstvu napiš jednou větou.", "Vyber jen to, co je pro tebe teď živé.", "Na konci přidej otázku pro chvíli, kdy nebudeš vědět."],
    steps: ["Co se ve mně obvykle ozve a co tehdy potřebuju?", "Který směr a způsob jednání si vybírám?", "Jaký nejmenší krok mě vrátí k sobě?"],
    prompt: "Jak zní moje krátká navigace pro další náročnou chvíli?",
    fields: [area("signal", "Když si všimnu…"), area("need", "Možná je pro mě důležité…"), area("value", "Chci chránit směr…"), area("identity", "Chci v této chvíli jednat jako člověk, který…"), area("step", "Můj nejmenší další krok"), area("returnQuestion", "Otázka, ke které se vrátím")],
  },
];
