import type { EmotionLesson } from "./emotionLessons";
import { IDENTITY_EDUCATION_COPY } from "./identityEducationCopy";
import { IDENTITY_EXPERT_COPY } from "./identityExpertCopy";
import { IDENTITY_OPENING_COPY } from "./identityOpeningCopy";
import { IDENTITY_PRACTICE_COPY } from "./identityPracticeCopy";
import { IDENTITY_RECOGNITION_COPY } from "./identityRecognitionCopy";
import { VALUE_EXPERT_COPY } from "./valuesExpertCopy";
import { VALUE_EDUCATION_COPY } from "./valuesEducationCopy";
import { VALUE_PRACTICE_COPY } from "./valuesPracticeCopy";
import { VALUE_RECOGNITION_COPY } from "./valuesRecognitionCopy";

type LessonSeed = {
  day: number;
  title: string;
  story: string;
  insight: string;
  example: string;
  question: string;
  practiceBullets?: string[];
  fields?: EmotionLesson["practice"]["fields"];
  closing: [string, string];
};

const field = (id: string, label: string, placeholder?: string) => ({
  id,
  label,
  type: "textarea" as const,
  placeholder,
  required: true,
});

const VALUE_DAY_TWO_COPY = {
  illustrationCaption:
    "Odpovědnost může zůstat. Změnit se může způsob, jakým ji žiješ.",
};

function createValuesLesson(seed: LessonSeed): EmotionLesson {
  const dayTwoCopy = seed.day === 2 ? VALUE_DAY_TWO_COPY : null;

  return {
    day: seed.day,
    opening: {
      eyebrow: "KRISTIÁNŮV VSTUP",
      title: seed.title,
      paragraphs: [seed.story],
    },
    recognition: VALUE_RECOGNITION_COPY[seed.day - 1],
    education: VALUE_EDUCATION_COPY[seed.day - 1],
    illustration: {
      src: `/prostor-assets/values-day-${String(seed.day).padStart(2, "0")}.webp`,
      alt: `Ručně kreslená vizualizace tématu hodnot pro den ${seed.day}`,
      caption: dayTwoCopy?.illustrationCaption ?? seed.insight,
    },
    expert: VALUE_EXPERT_COPY[seed.day - 1],
    practice: VALUE_PRACTICE_COPY[seed.day - 1],
    closing: seed.closing,
  };
}

function createIdentityLesson(seed: LessonSeed): EmotionLesson {
  return {
    day: seed.day,
    opening: IDENTITY_OPENING_COPY[seed.day - 1],
    recognition: IDENTITY_RECOGNITION_COPY[seed.day - 1],
    education: IDENTITY_EDUCATION_COPY[seed.day - 1],
    illustration: {
      src: `/prostor-assets/identity-day-${String(seed.day).padStart(2, "0")}.webp`,
      alt: `Ručně kreslená vizualizace identity a vize pro den ${seed.day}`,
      caption: seed.question,
    },
    expert: IDENTITY_EXPERT_COPY[seed.day - 1],
    practice: IDENTITY_PRACTICE_COPY[seed.day - 1],
    closing: seed.closing,
  };
}

const VALUE_SEEDS: LessonSeed[] = [
  { day: 1, title: "Moje kalendáře a rozhodnutí mi o hodnotách řekly víc než seznam hezkých slov.", story: "Když jsem se poprvé podíval na to, čemu dávám čas a energii, ne všechno odpovídalo tomu, co jsem o sobě říkal. Nebyl to důvod ke studu. Byla to první poctivá mapa. Začal jsem si každý večer vybírat jedno skutečné rozhodnutí a ptát se, co v něm dostalo přednost a co zůstalo stranou. Díky tomu jsem nepřemýšlel o hodnotách jako o ideálech. Začal jsem je vidět v běžném životě a mohl jsem některé další volby dělat vědoměji.", insight: "Hodnota se ukazuje v tom, čemu dáš přednost, když nemůžeš mít všechno.", example: "Říkáš, že jsou pro tebe důležité vztahy, ale všechen použitelný čas odevzdáš práci.", question: "Podle čeho jsem se rozhodl?", practiceBullets: ["Nehledej správné hodnocení svého rozhodnutí.", "Všimni si, co pro tebe v té chvíli bylo důležité.", "Zachyť také cenu, kterou tvoje volba přinesla."], closing: ["Nezačínej seznamem ideálů.", "Začni jedním rozhodnutím, které se opravdu stalo."] },
  { day: 2, title: "Dlouho jsem zaměňoval odpovědnost za pravidlo, že nesmím nikoho zklamat.", story: "Odpovědnost je pro mě důležitá. Jenže když jsem ji žil bez možnosti volby, změnila se v tlak, pod kterým jsem sliboval víc, než jsem mohl unést. Začal jsem před každým dalším ano kontrolovat svoji kapacitu a rozlišovat, jestli pomoc opravdu volím, nebo se jen bojím odmítnout. Naučil jsem se říkat, co zvládnu, co nezvládnu a kdy se k věci můžu vrátit. Odpovědnost mi zůstala. Přestal jsem ji ale dokazovat tím, že všechno unesu sám.", insight: "Stejné ano může vzniknout z volby i ze strachu.", example: "Pomůžeš, protože chceš být spolehlivý, ale uvnitř slyšíš hlavně větu „nesmím odmítnout“.", question: "Kolik prostoru pro volbu bylo v mém rozhodnutí?", closing: ["Stejný čin může mít dva různé zdroje.", "Ptej se, kolik v něm bylo skutečné volby."] },
  { day: 3, title: "Některé věty jsem si nevybral. Jen jsem je slyšel tak dlouho, až zněly jako moje.", story: "V rodině, škole i práci jsem se učil, co je správné, bezpečné a oceňované. Část toho mi slouží dodnes. Část jsem jen automaticky opakoval. Pomohlo mi tyto věty napsat na papír a u každé se zeptat, odkud ji znám, před čím mě chránila a jestli podle ní chci žít i dnes. Některé jsem si vědomě ponechal. Jiné jsem přepsal tak, aby v nich byla moje dnešní zkušenost a možnost volby.", insight: "Původ hodnoty neurčuje, jestli je dnes tvoje. Důležitá je vědomá volba.", example: "Žiješ podle věty „nejdřív povinnosti“, i když povinnosti nikdy nekončí.", question: "Odkud znám pravidlo, které mě dnes vedlo?", closing: ["Nemusíš odmítnout všechno převzaté.", "Můžeš si znovu vybrat, co chceš nést dál."] },
  { day: 4, title: "Výkon mi dlouho přinášel uznání. Proto jsem ho snadno zaměnil za vlastní hodnotu.", story: "Když jsem zvládl víc než ostatní, dostal jsem pozornost, respekt i pocit bezpečí. Dávalo smysl, že jsem se k výkonu vracel. Problém přišel, když jsem bez něj neuměl být v pořádku. Změna nezačala tím, že jsem přestal chtít podávat výkon. Začal jsem si všímat, co se ve mně děje ve chvíli, kdy zrovna nic nedokazuju. Učil jsem se zůstat se sebou i v nepříjemném pocitu, odpočívat dřív, než jsem si odpočinek zasloužil vyčerpáním, a přijmout pomoc, aniž by to pro mě znamenalo slabost. Výkon pro mě zůstal důležitý. Přestal ale být jediným důkazem mojí hodnoty. Dnes ho chci používat jako schopnost, ne jako podmínku, abych se sebou mohl být v pořádku.", insight: "To, co bylo odměňované, se může stát silným vnitřním kompasem.", example: "Odpočineš si až tehdy, když máš pocit, že sis klid zasloužil.", question: "Za co jsem získával uznání nebo pocit bezpečí?", closing: ["Odměna vysvětluje, proč se vzorec vrací.", "Nemusí ale rozhodovat o celé tvojí budoucnosti."] },
  { day: 5, title: "Abych byl přijatý, naučil jsem se některé části sebe držet stranou.", story: "Někdy jsem byl silný, užitečný a klidný i ve chvíli, kdy jsem potřeboval pomoc nebo chtěl něco jiného. Přijetí mělo cenu, kterou jsem dlouho neviděl. Začal jsem si v bezpečných vztazích zkoušet malé dávky upřímnosti. Říct, že nevím. Požádat o pomoc. Přiznat, že něco nechci. Ne každý vztah to unesl stejně, ale já jsem postupně poznal, že blízkost, ve které musím schovat sám sebe, není blízkost, kterou chci dál vytvářet.", insight: "Přizpůsobení může chránit vztah. Dlouhodobě ale může zakrýt vlastní směr.", example: "Souhlasíš rychleji, než vůbec zjistíš, co chceš ty.", question: "Co jsem se naučil potlačit, abych byl v pořádku?", closing: ["To, co tě kdysi chránilo, nemusíš odsuzovat.", "Dnes můžeš zkoumat, co už nemusíš skrývat."] },
  { day: 6, title: "Moje hodnoty nebyly vidět v prohlášeních. Byly vidět v úterý odpoledne.", story: "Když jsem chtěl vědět, co opravdu žiju, přestal jsem se ptát jen na ideály. Podíval jsem se na jednu schůzku, jednu odpověď a jednu chvíli únavy. U každé jsem si zapsal, co jsem udělal, co tím získalo prostor a co zaplatilo cenu. Tohle jednoduché pozorování mi dalo konkrétnější odpověď než dlouhý seznam hodnot. Postupně jsem mohl měnit malé činy, ve kterých moje důležité hodnoty dřív zůstávaly jen slovy.", insight: "Konkrétní čin je přesnější stopa než obecné tvrzení o sobě.", example: "O respektu mluvíš často, ale ve spěchu druhého nenecháš dokončit větu.", question: "Jakou hodnotu dnes ukázalo moje skutečné chování?", closing: ["Nejde o rozsudek nad charakterem.", "Jde o jeden čin, ze kterého se můžeš učit."] },
  { day: 7, title: "Po týdnu jsem nepotřeboval pořadí hodnot. Potřeboval jsem vidět opakující se směry.", story: "Některé situace ukazovaly péči, jiné výkon, svobodu nebo klid. Vedle nich se objevovala pravidla, která jsem plnil bez otázky. Teprve dohromady začala vznikat mapa. Jednou týdně jsem se k záznamům vracel a označil si, co jsem skutečně žil, co jsem dělal ze strachu a jaká cena se opakovala. Mapa za mě nerozhodovala. Pomáhala mi poznat stejné místo o něco dřív a příště do něj vstoupit s větším prostorem pro volbu.", insight: "První mapa odděluje žité hodnoty, převzatá pravidla a otázky k dalšímu zkoumání.", example: "Ve více situacích se vrací odpovědnost, ale také strach z toho, že zklameš.", question: "Které hodnoty a pravidla se u mě tento týden opakovaly?", fields: [field("livedValues", "Hodnoty, které jsem skutečně žil"), field("rules", "Pravidla, která jsem plnil bez volby"), field("cost", "Cena, kterou jsem někdy zaplatil"), field("nextQuestion", "Otázka, kterou si beru do další etapy")], closing: ["První mapa nemusí být přesná navždy.", "Stačí, když je poctivá dnes."] },
  { day: 8, title: "Slovo „musím“ mi často ukázalo místo, které stojí za bližší pohled.", story: "Ne každé „musím“ je problém. Některé povinnosti jsou skutečné. Jindy ale toto slovo zakrývalo strach, že bez výkonu, souhlasu nebo kontroly nejsem dost. Začal jsem si u těchto vět doplňovat tři otázky. Co se opravdu stane, když to neudělám? Co si volím, i když to není příjemné? A kde existuje jiná možnost? Nezmizely všechny povinnosti. Zmizela ale část automatického tlaku, ve kterém jsem dřív neviděl rozdíl mezi realitou a starým pravidlem.", insight: "Převzaté pravidlo často zní absolutně a nepřipouští kontext.", example: "Říkáš si „musím to zvládnout sám“, i když pomoc existuje.", question: "Které vnitřní pravidlo dnes řídilo moje rozhodnutí?", closing: ["Nezakazuj si slovo „musím“.", "Zeptej se, komu tato věta dnes slouží."] },
  { day: 9, title: "Když byla moje hodnota navázaná na výkon, žádný výsledek nestačil na dlouho.", story: "Úspěch přinesl krátkou úlevu. Pak se laťka posunula a já potřeboval další důkaz. Nešlo jen o ambici. Šlo o podmínku, pod kterou jsem si dovolil cítit se dost. Začal jsem proto oddělovat hodnocení výsledku od hodnocení sebe. Mohl jsem se podívat, co se povedlo, co potřebuje opravit a co se chci naučit, aniž bych z jedné práce dělal rozsudek nad celým člověkem. Postupně jsem hledal hodnotu také ve vztazích, pravdivosti, péči a odvaze. Výkon zůstal součástí mého života, ale přestal v něm mít jediné hlasovací právo.", insight: "Podmínka vlastní hodnoty říká, co musíš splnit, abys mohl být v pořádku.", example: "Cítíš se hodnotný hlavně tehdy, když jsi užitečný pro ostatní.", question: "Co mám pocit, že musím splnit, abych byl dost?", closing: ["Výsledek může být důležitý.", "Nemusí rozhodovat o tvojí lidské hodnotě."] },
  { day: 10, title: "Odpovědnost mi slouží, když mi pomáhá držet slovo a zároveň vidět svoje limity.", story: "Nechtěl jsem svoje hodnoty zahodit. Potřeboval jsem najít jejich zdravou podobu. U odpovědnosti jsem si proto začal předem určovat, co opravdu slibuju, kdy požádám o pomoc a podle čeho poznám, že už překračuju svoji kapacitu. Díky tomu jsem mohl držet slovo, aniž jsem se pravidelně dostával za vlastní hranice. Hodnota zůstala stejná. Změnil se způsob, jakým ji žiju.", insight: "Zdravá hodnota respektuje realitu, kontext a důstojnost všech zúčastněných.", example: "Jsi spolehlivý a zároveň dokážeš včas říct, že něco nezvládneš.", question: "Jak moje důležitá hodnota vypadá ve zdravé podobě?", closing: ["Hodnota nemusí bolet, aby byla opravdová.", "Může vést pevně a zároveň lidsky."] },
  { day: 11, title: "I dobrá hodnota se může stát tvrdým nástrojem, když ji použiju bez kontextu.", story: "Pravda může být upřímnost, ale také záminka pro tvrdost. Péče může být blízkost, ale také kontrola. Výkon může být mistrovství, ale také útěk od sebe. Pomohlo mi přestat se ptát jen, jestli jednám podle své hodnoty. Začal jsem sledovat také způsob a dopad. Co se snažím chránit? Respektuje moje jednání mě i druhého? Tohle mi dovolilo hodnotu zachovat a současně změnit podobu, ve které dřív zraňovala nebo vytvářela tlak.", insight: "Extrém hodnoty poznáš podle ztráty flexibility a rostoucí ceny.", example: "Ve jménu pravdy řekneš něco způsobem, který druhého zbytečně zraní.", question: "Kdy se moje hodnota mění v tlak na mě nebo na druhé?", closing: ["Silná hodnota nepotřebuje bezohlednost.", "Zralost poznáš podle prostoru pro kontext."] },
  { day: 12, title: "Některá rozhodnutí bolela proto, že proti sobě nestálo dobro a zlo, ale dvě důležité věci.", story: "Chtěl jsem být s rodinou a zároveň dokončit práci, na které mi záleželo. Chtěl jsem být pravdivý a současně laskavý. Neexistovala volba bez ceny. Dřív jsem hledal řešení, ve kterém neztratím nic, a tím rozhodnutí jen prodlužoval. Začal jsem si obě hodnoty pojmenovávat nahlas, zvolit prioritu pro konkrétní chvíli a přijmout cenu bez znehodnocení toho druhého. Rozhodování nebylo vždy lehké. Bylo ale poctivější a srozumitelnější pro mě i pro lidi kolem.", insight: "Střet hodnot není selhání. Je to situace, ve které potřebuješ vědomou prioritu.", example: "Volíš mezi odpočinkem a závazkem, který jsi slíbil.", question: "Které dvě důležité hodnoty se dnes dostaly do střetu?", closing: ["Konflikt hodnot neznamená, že jednu z nich nemáš.", "Znamená, že dnes nemohly dostat všechno."] },
  { day: 13, title: "Vědomá volba mi nepřinesla vždy pohodlí. Přinesla mi ale odpovědnost za směr.", story: "Když jsem si přiznal, co upřednostňuju, mohl jsem přijmout i cenu. Nemusel jsem si tvrdit, že druhá hodnota není důležitá. Začal jsem svou volbu formulovat jednou jasnou větou a říct ji lidem, kterých se týkala. Potom jsem hledal, jak se můžu k odsunuté hodnotě vrátit později. Volba nepřestala mít cenu. Přestal jsem se v ní ale ztrácet.", insight: "Priorita je dočasná volba v konkrétním kontextu, ne konečné pořadí celého života.", example: "Dnes dáš přednost odpočinku a zároveň naplánuješ, kdy splníš závazek.", question: "Čemu chci v této chvíli dát přednost a proč?", closing: ["Priorita není zrada všeho ostatního.", "Je to poctivá volba pro tuto chvíli."] },
  { day: 14, title: "Když jsem viděl svoje opakující se konflikty, přestal jsem každé rozhodnutí prožívat jako nový chaos.", story: "U mě se vracel střet odpovědnosti a odpočinku, výkonu a vztahů, svobody a závazku. Mapa mi nedala univerzální řešení. Dala mi otázky, které jsem mohl použít příště. Před podobným rozhodnutím jsem se začal ptát: Co se střetává? Čemu dávám přednost právě teď? Jak chci pečovat o to, co dnes ustoupí? Opakující se chaos se změnil ve známé místo, ve kterém dokážu jednat vědoměji.", insight: "Mapa konfliktů ukazuje, které hodnoty se střetávají a jakou cenu obvykle platíš.", example: "Znovu a znovu zachraňuješ termín na úkor spánku a blízkých lidí.", question: "Které hodnotové střety se u mě vracejí?", fields: [field("conflict", "Dvě hodnoty, které se často střetávají"), field("usualChoice", "Čemu obvykle dám přednost"), field("price", "Jakou cenu obvykle zaplatím"), field("newQuestion", "Jakou otázku si chci příště položit")], closing: ["Mapa konflikt neodstraní.", "Pomůže ti do něj vstoupit o něco vědoměji."] },
  { day: 15, title: "Ne všechno jsem potřeboval měnit. Některé hodnoty už můj život držely pohromadě.", story: "Když jsem se díval jen na problémy, přehlížel jsem spolehlivost, odvahu, péči i pravdivost, které už byly součástí mého života. Potřeboval jsem je uvidět a chránit.", insight: "Změna nezačíná pouze opravou. Může začít rozpoznáním toho, co už funguje.", example: "I v náročném týdnu držíš domluvy, které jsou pro tebe skutečně důležité.", question: "Kterou žitou hodnotu chci vědomě zachovat?", closing: ["Nemusíš přestavět celý život.", "Začni tím, co už v tobě stojí pevně."] },
  { day: 16, title: "Některá pravidla jsem mohl pustit, aniž bych ztratil to dobré, co kdysi chránila.", story: "Nemusel jsem zahodit odpovědnost. Mohl jsem pustit pravidlo, že všechno musím unést sám. Nemusel jsem odmítnout výkon. Mohl jsem přestat dokazovat, že mám hodnotu jen díky němu.", insight: "Pustit pravidlo neznamená opustit hodnotu. Znamená najít svobodnější způsob jejího života.", example: "Můžeš být pečující, aniž jsi dostupný každému kdykoliv.", question: "Které pravidlo už nechci dál dokazovat?", closing: ["Můžeš zachovat podstatu.", "A pustit způsob, který tě vyčerpává."] },
  { day: 17, title: "Zvolená hodnota pro mě začala být opravdová až ve chvíli, kdy nebyla závislá na potlesku.", story: "Když nikdo nevidí můj čin, zůstává otázka, jakým člověkem chci být já sám. Právě tam se hodnota mění z obrazu pro druhé ve vlastní směr.", insight: "Vědomě zvolená hodnota je směr, ke kterému se chceš vracet i bez vnější odměny.", example: "Uděláš poctivou práci, i když za ni nedostaneš okamžité uznání.", question: "Jaký směr si vybírám, i když ho nikdo neocení?", closing: ["Hodnota není představení pro publikum.", "Je to směr, který poznáš i v tichu."] },
  { day: 18, title: "Slovo „respekt“ mi nepomohlo, dokud jsem nevěděl, co udělám při příštím náročném rozhovoru.", story: "Potřeboval jsem hodnotu přeložit do pozorovatelného chování. Naslouchat bez přerušení. Říct pravdu bez útoku. Požádat o čas místo zmizení.", insight: "Hodnota je použitelná, když ji dokážeš popsat jako konkrétní čin v konkrétní situaci.", example: "Místo věty „budu laskavější“ si zvolíš „nechám druhého dokončit první větu“.", question: "Jak bude moje zvolená hodnota zítra konkrétně vidět?", closing: ["Velké slovo potřebuje malý čin.", "Jinak zůstane jen přáním."] },
  { day: 19, title: "Začal jsem sbírat malé důkazy, ne čekat na velkou proměnu.", story: "Jeden rozhovor, ve kterém jsem zůstal pravdivý a klidný, nebyl konečná změna. Byl to ale skutečný důkaz směru, který jsem si vybral.", insight: "Malý důkaz posiluje schopnost vrátit se ke zvolené hodnotě i příště.", example: "Řekneš včas „ne“, aniž druhého shodíš nebo se dlouze omlouváš.", question: "Jaký drobný čin dnes potvrdil moji zvolenou hodnotu?", closing: ["Jeden čin není celá identita.", "Je to ale skutečný důkaz směru."] },
  { day: 20, title: "Hodnotu jsem potřeboval testovat v životě, ne jen obdivovat na papíře.", story: "Vybral jsem si jeden týden, jednu hodnotu a tři běžné situace. Nesledoval jsem dokonalost. Sledoval jsem, co mi pomáhá, co mě vrací do automatu a jaký je dopad.", insight: "Bezpečný experiment převádí hodnotu do praxe a sbírá data místo sebekritiky.", example: "Sedm dní testuješ, jak vypadá respekt v jednom pracovním rozhovoru denně.", question: "Jak budu sedm dní testovat jednu zvolenou hodnotu?", fields: [field("value", "Hodnota, kterou chci testovat"), field("situations", "Tři běžné situace, ve kterých ji zkusím žít"), field("behavior", "Konkrétní chování, které budu sledovat"), field("impact", "Čeho si po každém pokusu všimnu")], closing: ["Experiment není zkouška charakteru.", "Je to způsob, jak dát hodnotě skutečný život."] },
  { day: 21, title: "Můj manifest není seznam správných slov. Je to dohoda se sebou o směru.", story: "Po třech týdnech jsem nepotřeboval tvrdší pravidla. Potřeboval jsem několik jasných vět o tom, co chci chránit, jak to bude vidět a co udělám, když se hodnoty dostanou do konfliktu.", insight: "Osobní manifest propojuje zvolený směr, konkrétní chování a laskavou opravu po odchýlení.", example: "Místo „vždy budu pravdivý“ napíšeš, jak chceš pravdu spojovat s respektem a kontextem.", question: "Podle čeho chci žít a jak to poznám v běžném životě?", fields: [field("chosenValues", "Moje tři zvolené hodnoty"), field("behaviors", "Jak budou vidět v mém běžném chování"), field("oldRule", "Pravidlo, které už nechci dokazovat"), field("conflict", "Jak chci zacházet se střetem hodnot"), field("experiment", "Jeden čin na příštích sedm dní"), field("manifest", "Moje krátká dohoda se sebou")], closing: ["Manifest tě nemá svázat.", "Má ti připomenout směr, ke kterému se chceš vracet."] },
];

const IDENTITY_SEEDS: LessonSeed[] = [
  { day: 1, title: "Dlouho jsem věděl, co všechno dělám. Hůř se mi odpovídalo, kdo jsem mimo svoje funkce.", story: "Byl jsem člověk, který rozhoduje, vede, pomáhá a nese odpovědnost. Role mi dávaly smysl i uznání. Když jsem je ale na chvíli odložil, objevilo se ticho, ve kterém jsem se potřeboval znovu poznat.", insight: "Role jsou důležité části života. Nejsou ale celým člověkem.", example: "Dokážeš popsat svoji práci a povinnosti, ale ne to, co je ti vlastní mimo ně.", question: "Ve kterých rolích dnes trávím nejvíc života?", closing: ["Role mohou nést smysl.", "Nemusí ale unést celou tvoji identitu."] },
  { day: 2, title: "Když na chvíli odložím výkon, pořád ve mně zůstává člověk, který něco cítí, potřebuje a volí.", story: "Pro mě bylo nezvyklé být chvíli bez úkolu. Jako by moje hodnota potřebovala neustálý důkaz. Postupně jsem objevoval kvality, které nejsou funkcí ani výsledkem.", insight: "Mimo role můžeš hledat kvality, vztah k sobě a způsob, jakým chceš být přítomný.", example: "Volný čas tě znervózní, protože v něm nevíš, čím dokazuješ svoji hodnotu.", question: "Co ze mě zůstává, když na chvíli odložím role a výkon?", closing: ["Nejsi jen to, co zvládáš.", "Jsi také způsob, jakým u sebe dokážeš být."] },
  { day: 3, title: "Některé příběhy o sobě jsem opakoval tak dlouho, až jsem přestal hledat výjimky.", story: "Věty jako „já už jsem takový“ nebo „já vždycky všechno pokazím“ zněly jako fakta. Ve skutečnosti to byly zkratky vytvořené z části zkušeností.", insight: "Příběh o sobě vybírá některé důkazy a jiné snadno přehlédne.", example: "Jedno odmítnutí používáš jako důkaz, že ve vztazích nejsi dost dobrý.", question: "Jakou větu o sobě opakuju tak dlouho, až zní jako fakt?", closing: ["Příběh může obsahovat pravdivou zkušenost.", "Nemusí být poslední větou o tobě."] },
  { day: 4, title: "Nálepka mi dávala rychlé vysvětlení. Zároveň mi brala prostor zkusit něco jinak.", story: "Když jsem si řekl, že jsem prostě tvrdý, uzavřený nebo příliš odpovědný, nemusel jsem zkoumat kontext. Nálepka byla jednoduchá. Život pod ní ale zůstával stejný.", insight: "Nálepka shrnuje. Identita může zůstat otevřená novým důkazům.", example: "Řekneš „jsem introvert“, a proto automaticky odmítneš každý nový kontakt.", question: "Která moje nálepka už nedává prostor změně?", closing: ["Nálepka může něco popsat.", "Neměla by rozhodnout, co už nikdy nemůžeš zkusit."] },
  { day: 5, title: "Změna nezačala z nuly. Mnoho kvalit, které jsem hledal, už se objevovalo v malých chvílích.", story: "Odvaha nebyla jen velké rozhodnutí. Byla i chvíle, kdy jsem řekl pravdu. Péče nebyla jen starost o druhé. Byla i desetiminutová pauza, kterou jsem si dovolil.", insight: "Existující důkazy pomáhají stavět směr na realitě, ne na odmítnutí dnešního já.", example: "Myslíš si, že nejsi odvážný, ale přehlížíš situace, ve kterých jsi už jednal navzdory strachu.", question: "Které kvality už dnes dokazuju svými činy?", closing: ["Nemusíš čekat, až se staneš někým novým.", "Nejdřív uvidíš, co už v tobě opravdu je."] },
  { day: 6, title: "Každodenní činy potvrzovaly určitý příběh o mně, ať jsem ho zvolil vědomě, nebo ne.", story: "Když jsem pokaždé odpověděl hned, potvrzoval jsem roli člověka, který je vždy dostupný. Když jsem začal chránit soustředění, vznikal nový důkaz, že můj čas má hranice.", insight: "Opakované chování posiluje identitu, kterou potom považuješ za samozřejmou.", example: "Každým automatickým souhlasem potvrzuješ příběh „moje potřeby počkají“.", question: "Jakou identitu dnes posilují moje běžné volby?", closing: ["Identitu netvoří jen velké sliby.", "Tvoří ji i malé automatické ano a ne."] },
  { day: 7, title: "Moje dnešní identita byla směsí rolí, starých vět i skutečných důkazů.", story: "Když jsem je oddělil, přestal jsem se soudit jednou větou. Viděl jsem, co dnes žiju, co si o sobě pouze vyprávím a kde už existuje prostor pro jiný směr.", insight: "Mapa dnešní identity odděluje role, příběhy, kvality a opakované chování.", example: "V roli vedoucího se považuješ za člověka, který nesmí ukázat nejistotu, i když už umíš otevřeně požádat o názor.", question: "Které role, příběhy a důkazy dnes tvoří moji mapu?", fields: [field("roles", "Role, ve kterých dnes žiju"), field("stories", "Věty, které si o sobě opakuju"), field("qualities", "Kvality, pro které už mám důkazy"), field("patterns", "Co opakovaně potvrzuju"), field("question", "Kterého svého chování si chci příští týden všímat")], closing: ["Mapa dneška není rozsudek.", "Je to místo, ze kterého můžeš vědomě vyjít."] },
  { day: 8, title: "Přestal jsem čekat na hotovou verzi sebe. Začal jsem hledat směr.", story: "Dokonalý obraz budoucího já mě spíš paralyzoval. Směr byl praktičtější. Nemusel jsem být hotový. Potřeboval jsem jen vědět, kam chci udělat další krok.", insight: "Směr umožňuje pokrok bez požadavku na dokonalou proměnu.", example: "Místo cíle „už nikdy se nebát“ hledáš směr „jednat odvážně i s přítomným strachem“.", question: "Jakým směrem se chci posouvat bez požadavku být hotový?", closing: ["Nemusíš vidět celou cestu.", "Potřebuješ směr, který dává smysl dalšímu kroku."] },
  { day: 9, title: "Otázka nebyla jen, čeho chci dosáhnout. Byla také, jakým člověkem chci být cestou.", story: "Stejný cíl můžu naplnit tlakem, manipulací nebo spoluprací. Výsledek sám neřekne, jakou kvalitu jsem do života přinesl.", insight: "Zvolená identita popisuje kvalitu jednání, ne jen budoucí pozici nebo výsledek.", example: "Nechceš být pouze úspěšný vedoucí. Chceš být člověk, který vede jasně a lidsky.", question: "Jakou kvalitu chci přinášet do běžných situací?", closing: ["Cíl říká, čeho chceš dosáhnout.", "Identita připomíná, jakým člověkem chceš být cestou."] },
  { day: 10, title: "Kým chci být ve vztahu, se nejvíc ukáže ve chvíli, kdy se neshodneme.", story: "Bylo snadné být laskavý, když bylo všechno v pořádku. Můj směr se ukázal ve chvíli napětí, kdy jsem mohl naslouchat, říct hranici nebo se po chybě vrátit.", insight: "Vztahová identita se projevuje v kontaktu, hranicích, opravě a schopnosti nechat druhého být jiný.", example: "Chceš být blízký člověk, ale konflikt řešíš stažením bez vysvětlení.", question: "Kým chci být ve chvíli, kdy je vztah náročný?", closing: ["Kvalitu vztahu netvoří absence konfliktu.", "Tvoří ji i způsob, jakým se k sobě vracíte."] },
  { day: 11, title: "Práce dlouho nebyla jen tím, co dělám. Stala se hlavním důkazem, kdo jsem.", story: "Když se práce dařila, cítil jsem hodnotu. Když se nedařila, otřáslo to celým obrazem sebe. Potřeboval jsem znovu zvolit, jakým člověkem chci být při výkonu i neúspěchu.", insight: "Pracovní role může být důležitá, aniž pohltí celou identitu.", example: "Jednu chybu v práci prožiješ jako důkaz, že jsi selhal jako člověk.", question: "Jakým člověkem chci být při práci, vedení a spolupráci?", closing: ["Práce může vyjadřovat tvoje hodnoty.", "Nemusí nést celou tvoji lidskou cenu."] },
  { day: 12, title: "Péče o sebe pro mě začala být součást identity, ne odměna po výkonu.", story: "Když jsem odpočinek bral jen jako přestávku před další prací, nikdy neměl vlastní hodnotu. Nový směr zněl jinak. Jsem člověk, který bere vážně svoji kapacitu.", insight: "Identita péče se potvrzuje způsobem, jak zacházíš s tělem, hranicemi a obnovou.", example: "Říkáš, že zdraví je důležité, ale spánek pravidelně použiješ jako rezervu pro práci.", question: "Jak se k sobě chová člověk, kterým se chci stávat?", closing: ["Péče není odměna za bezchybný výkon.", "Může být způsob, jakým se sebou žiješ každý den."] },
  { day: 13, title: "Nový příběh potřeboval malý důkaz ještě dnes.", story: "Věta „jsem člověk, který se umí zastat sám sebe“ získala váhu až ve chvíli, kdy jsem v jedné malé situaci řekl jasné ne nebo požádal o čas.", insight: "Důkaz identity je malý pozorovatelný čin, který potvrzuje zvolený směr.", example: "Jednou dnes odložíš automatickou odpověď a nejdřív zjistíš, co chceš ty.", question: "Jaký malý čin dnes potvrdí můj zvolený směr?", closing: ["Nemusíš nový příběh dokazovat všude.", "Stačí jeden skutečný čin, na kterém můžeš stavět."] },
  { day: 14, title: "Budoucí já pro mě přestalo být plakát. Stalo se sadou vět, které můžu dokazovat životem.", story: "Nechtěl jsem si představovat bezchybnou postavu. Chtěl jsem vidět člověka, který se vrací k pravdě, vztahům, péči a odvaze i po dnech, kdy se mu to nepodaří.", insight: "Mapa budoucího já propojuje zvolenou kvalitu, kontext a konkrétní důkazy.", example: "Místo „budu sebevědomý“ volíš „dokážu říct svůj názor a zůstat otevřený odpovědi“.", question: "Které věty o svém směru chci začít dokazovat životem?", fields: [field("relationshipIdentity", "Kým se chci stávat ve vztazích"), field("workIdentity", "Kým se chci stávat v práci"), field("selfCareIdentity", "Kým se chci stávat v péči o sebe"), field("evidence", "Tři malé důkazy na příští týden")], closing: ["Budoucí já není cizí dokonalá postava.", "Je to směr, který může začít jedním dnešním činem."] },
  { day: 15, title: "Vize mi začala dávat smysl, když jsem si představil obyčejné úterý, ne jen velké cíle.", story: "Jak vstávám. S kým mluvím. Čemu dávám pozornost. Jak pracuju. Jak vypadá večer. Právě v obyčejném dni se ukázalo, jestli je vize opravdu moje.", insight: "Vize běžného dne odhaluje rytmus a podmínky života, ne pouze seznam výsledků.", example: "Přeješ si svobodu, ale tvoje vysněné úterý je zaplněné závazky od rána do noci.", question: "Jak vypadá obyčejný den života, který mi dává smysl?", closing: ["Vize nemusí začít vrcholem.", "Začni obyčejným dnem, ve kterém chceš opravdu žít."] },
  { day: 16, title: "Ve vizi vztahů jsem nehledal jen správné lidi. Díval jsem se, jakým člověkem v kontaktu budu já.", story: "Jak mluvím, když se bojím. Jak naslouchám, když nesouhlasím. Jak chráním hranici bez trestu. Jak se vracím po chybě. Tohle byly části vize, které jsem mohl ovlivnit.", insight: "Vize vztahů zahrnuje kvalitu kontaktu i vlastní odpovědnost, ne kontrolu druhých.", example: "Přeješ si otevřený vztah, ale těžké téma stále odkládáš bez vysvětlení.", question: "Jak chci ve vztazích mluvit, naslouchat a chránit hranice?", closing: ["Vizi vztahu netvoříš sám.", "Můžeš ale zvolit, co do něj přinášíš ty."] },
  { day: 17, title: "Práce ve vizi nebyla jen pozice nebo příjem. Byla to energie, způsob tvorby a přínos.", story: "Začal jsem si všímat, jaké problémy chci řešit, s jakými lidmi, jakým tempem a za jakou cenu. Peníze zůstaly důležité. Už ale nebyly jedinou odpovědí.", insight: "Smysluplná pracovní vize spojuje přínos, podmínky, energii a realistické potřeby.", example: "Toužíš po smysluplné práci, ale zatím nevíš, jaký konkrétní problém chceš pomáhat řešit.", question: "Čemu chci věnovat energii a jaký dopad mi dává smysl?", closing: ["Práce nemusí být celý smysl života.", "Může ale být vědomou částí toho, čemu dáváš energii."] },
  { day: 18, title: "Nový směr se žil snadněji, když jsem přestal ignorovat prostředí a kapacitu.", story: "Nestačilo chtít být klidnější, tvořivější nebo přítomnější. Potřeboval jsem čas bez přerušení, spánek, lidi, kteří respektují hranice, a méně zbytečných vstupů.", insight: "Prostředí může zvyšovat nebo snižovat pravděpodobnost chování, které chceš žít.", example: "Chceš tvořit, ale celý den nemáš jediný chráněný úsek bez notifikací.", question: "Jaké prostředí a podmínky mi pomáhají žít tak, jak chci?", closing: ["Ne všechno je otázka vůle.", "Některé změny potřebují vhodnější podmínky."] },
  { day: 19, title: "Mezi dneškem a vizí bylo mnoho rozdílů. Potřeboval jsem vybrat ten, který má největší význam.", story: "Kdybych chtěl změnit všechno, neudělal bych nic. Hledal jsem jeden rozdíl, který ovlivňuje více oblastí. Často to byla kapacita, hranice nebo způsob, jak zacházím s časem.", insight: "Nejdůležitější rozdíl není vždy největší. Je to ten, jehož změna může otevřít další možnosti.", example: "Vize obsahuje blízkost i zdraví, ale současný pracovní rytmus bere prostor obojímu.", question: "Ve které oblasti je dnes největší rozdíl mezi realitou a mojí vizí?", closing: ["Nemusíš změnit všechno najednou.", "Vyber jeden rozdíl, který může otevřít další prostor."] },
  { day: 20, title: "Nejmenší krok nebyl málo. Byl to most mezi představou a skutečným životem.", story: "Místo velkého rozhodnutí jsem hledal čin na sedm dní. Jednu domluvu. Jeden blok času. Jeden rozhovor. Něco, co vytvoří skutečná data a další možnost.", insight: "Malý krok s jasným časem a kontextem má větší šanci stát se důkazem než obecný závazek.", example: "Místo „budu víc s rodinou“ domluvíš jeden večer bez pracovního telefonu.", question: "Co můžu udělat během sedmi dní, aniž měním celý život?", fields: [field("gap", "Mezera, na kterou reaguju"), field("step", "Jeden nejmenší krok"), field("when", "Kdy a kde ho udělám"), field("support", "Co mi pomůže krok uskutečnit"), field("observe", "Čeho si potom všimnu")], closing: ["Malý krok není zmenšená vize.", "Je to první místo, kde se vize dotkne reality."] },
  { day: 21, title: "Osobní kompas mi nedal hotovou odpověď na celý život. Dal mi způsob, jak se k sobě vracet.", story: "Propojil jsem emoce, potřeby, hodnoty, role, zvolenou identitu a směr. Ne proto, abych měl všechno pod kontrolou. Proto, abych v další náročné chvíli věděl, na co se můžu zeptat.", insight: "Osobní kompas je živá mapa. Může se měnit s novými zkušenostmi a vědomými volbami.", example: "Když se objeví nejistota, místo automatické reakce se vrátíš k potřebě, hodnotě a nejmenšímu dalšímu kroku.", question: "Kdo jsem, kým se stávám a jaký krok si beru dál?", fields: [field("today", "Kdo jsem dnes a co už o sobě vím"), field("roles", "Role, které chci žít vědoměji"), field("identity", "Kým se chci stávat"), field("vision", "Jak vypadá život, který chci postupně vytvářet"), field("conditions", "Podmínky, které můj směr podporují"), field("step", "Nejmenší další krok na sedm dní"), field("question", "Otázka, ke které se chci vracet")], closing: ["Kompas nerozhoduje za tebe.", "Pomáhá ti vracet se k sobě a znovu volit směr."] },
];

export const VALUES_LESSONS = VALUE_SEEDS.map(createValuesLesson);
export const IDENTITY_LESSONS = IDENTITY_SEEDS.map(createIdentityLesson);

export function getValuesLesson(day: number) {
  return VALUES_LESSONS.find((lesson) => lesson.day === day) ?? VALUES_LESSONS[0];
}

export function getIdentityLesson(day: number) {
  return IDENTITY_LESSONS.find((lesson) => lesson.day === day) ?? IDENTITY_LESSONS[0];
}
