import type { EmotionLesson } from "./emotionLessons";

type Practice = EmotionLesson["practice"];
type Field = NonNullable<Practice["fields"]>[number];

const text = (id: string, label: string, placeholder?: string): Field => ({
  id, label, type: "text", placeholder, required: true,
});
const area = (id: string, label: string, placeholder?: string): Field => ({
  id, label, type: "textarea", placeholder, required: true,
});
const scale = (id: string, label: string): Field => ({
  id, label, type: "scale", required: true,
});

export const VALUE_PRACTICE_COPY: Practice[] = [
  {
    title: "Udělej tříminutovou inventuru včerejška.",
    why: "Místo hledání ideálních hodnot přečteš tři obyčejné stopy z času, energie a jedné volby.",
    whyBullets: ["Vezmi včerejšek, ne výjimečný životní okamžik.", "Najdi tři místa, kam skutečně odešel čas nebo energie.", "Vyber stopu, která tě nejvíc překvapila."],
    steps: ["Kde včera skončila největší část mé volné energie?", "Co díky tomu dostalo prostor?", "Co kvůli tomu zůstalo stranou?"],
    prompt: "Co o mých prioritách ukazuje jeden obyčejný den?",
    fields: [area("trace", "Jedna konkrétní stopa ze včerejška"), text("space", "Co dostalo prostor"), text("aside", "Co zůstalo stranou")],
  },
  {
    title: "Vlož mezi požadavek a odpověď deset vteřin.",
    why: "Krátká pauza ti umožní zachytit rozdíl mezi skutečným ano a automatickým souhlasem.",
    whyBullets: ["Vyber jednu malou prosbu, ne krizovou situaci.", "Před odpovědí zkontroluj kalendář, tělo a chuť.", "Odpověz ano, ne nebo navrhni jinou možnost."],
    steps: ["Co po mně druhý chtěl?", "Jaké tři odpovědi byly skutečně možné?", "Kterou z nich jsem po pauze zvolil?"],
    prompt: "Co se změnilo, když jsem neodpověděl okamžitě?",
    fields: [area("request", "Konkrétní požadavek"), area("options", "Tři možné odpovědi"), area("choice", "Moje vědomá odpověď a její dopad")],
  },
  {
    title: "Nakresli rodokmen jedné věty.",
    why: "Staré pravidlo rozložíš na původ, původní užitek a dnešní rozhodnutí.",
    whyBullets: ["Zachyť větu přesně tak, jak ti zní v hlavě.", "Dohledej člověka nebo prostředí, odkud ji znáš.", "Rozhodni, co z ní chceš zachovat a co přepsat."],
    steps: ["Která věta mě dnes řídila?", "Odkud ji znám a co tehdy chránila?", "Jak by zněla její moje dnešní verze?"],
    prompt: "Kterou převzatou větu si chci znovu vybrat po svém?",
    fields: [text("rule", "Původní věta"), area("origin", "Odkud ji znám a čemu sloužila"), area("rewrite", "Moje dnešní verze")],
  },
  {
    title: "Zastav na chvíli pohyblivou cílovou čáru.",
    why: "Uvidíš, zda výsledek může být výsledkem, nebo se okamžitě mění v další zkoušku vlastní hodnoty.",
    whyBullets: ["Vyber něco, co se ti nedávno podařilo.", "Zachyť první minuty po dokončení.", "Všimni si, kdy se objevilo další „ještě bych měl“."],
    steps: ["Co jsem dokončil nebo zvládl?", "Jak dlouho jsem si dovolil výsledek přijmout?", "Jaká další podmínka se objevila?"],
    prompt: "Co se stane, když výsledek na chvíli nemusí nic dokazovat?",
    fields: [area("result", "Co se mi podařilo"), text("relief", "Jak dlouho vydržela spokojenost"), area("nextDemand", "Jaký další požadavek se objevil"), area("otherWorth", "Co má ve mně hodnotu i bez tohoto výsledku")],
  },
  {
    title: "Vyzkoušej jednu mikrodávku pravdivosti.",
    why: "Nemusíš odhalit všechno. Zkusíš bezpečně ukázat jednu malou preferenci, kterou běžně schováš.",
    whyBullets: ["Vyber vztah, ve kterém je malé vyjádření bezpečné.", "Řekni jednu preferenci bez dlouhé obhajoby.", "Sleduj reakci druhého i vlastní tělo."],
    steps: ["Co bych běžně nechal nevyřčené?", "Jak to můžu říct jednou klidnou větou?", "Co se skutečně stalo potom?"],
    prompt: "Jaké to je ukázat malý kousek sebe a zůstat v kontaktu?",
    fields: [area("hidden", "Co běžně schovám"), text("sentence", "Moje jedna pravdivá věta"), area("impact", "Reakce druhého a moje prožívání")],
  },
  {
    title: "Pusť na jednu situaci pomyslnou kameru.",
    why: "Oddělíš hodnotu, kterou o sobě říkáš, od chování, které by mohl vidět nezaujatý pozorovatel.",
    whyBullets: ["Vyber jednu krátkou scénu z dneška.", "Popiš jen slova, pohyby a rozhodnutí.", "Teprve potom pojmenuj hodnotu, kterou čin podpořil."],
    steps: ["Co by bez výkladu zachytila kamera?", "Čemu moje jednání dalo přednost?", "Který jeden detail bych příště změnil?"],
    prompt: "Jakou hodnotu ukázal můj čin bez komentáře?",
    fields: [area("camera", "Záznam pomyslné kamery"), text("value", "Hodnota viditelná v činu"), area("edit", "Jeden detail pro příští pokus")],
  },
  {
    title: "Rozděl týdenní stopy do tří hromádek.",
    why: "Z jednotlivých dnů vytvoříš mapu: svobodná volba, automatické pravidlo a opakující se cena.",
    whyBullets: ["Vyber tři až pět rozhodnutí z týdne.", "Každé přiřaď do hromádky, která mu je nejblíž.", "Hledej opakování, ne vítěznou hodnotu."],
    steps: ["Kde jsem jednal v souladu se sebou?", "Kde mě vedlo hlavně staré pravidlo?", "Jaká cena se objevila více než jednou?"],
    prompt: "Jaký vzorec se ukáže, když položím několik dní vedle sebe?",
    fields: [area("chosen", "Hromádka: vědomě zvolené"), area("automatic", "Hromádka: automatické pravidlo"), area("price", "Hromádka: opakující se cena"), text("pattern", "Jedna stopa pro další týden")],
  },
  {
    title: "Prožeň jedno „musím“ detektorem reality.",
    why: "Rozlišíš skutečný závazek od části tlaku, kterou vytváří absolutní vnitřní pravidlo.",
    whyBullets: ["Zapiš dnešní „musím“ beze změny.", "Odděl reálné důsledky od obávaného hodnocení.", "Najdi nejmenší část, ve které stále existuje volba."],
    steps: ["Co je v této situaci opravdu dané?", "Čeho se obávám, kdybych postupoval jinak?", "Co můžu změnit v čase, rozsahu nebo způsobu?"],
    prompt: "Kde uvnitř povinnosti ještě zůstává moje volba?",
    fields: [text("must", "Moje věta „musím…“"), area("facts", "Skutečné závazky a důsledky"), area("fear", "Obávané hodnocení nebo ztráta"), area("choice", "Část, kterou stále můžu zvolit")],
  },
  {
    title: "Doplň chybějící větu za výkonem.",
    why: "Odhalíš podmínku, kterou výsledek možná nevědomě přikládá k tvé lidské hodnotě.",
    whyBullets: ["Vyber situaci, ve které chceš podat dobrý výkon.", "Dokonči větu bez cenzury.", "Přidej jiný zdroj hodnoty, který výsledek nemůže vzít."],
    steps: ["Když se mi to podaří, bude to znamenat, že…", "Když se mi to nepodaří, bojím se, že to znamená…", "Co o mně zůstane pravdivé v obou případech?"],
    prompt: "Jakou podmínku vlastní hodnoty dnes můžu uvidět přesněji?",
    fields: [area("successMeaning", "Když uspěju, znamená to…"), area("failureMeaning", "Když neuspěju, bojím se, že…"), area("both", "Co o mně platí v obou výsledcích")],
  },
  {
    title: "Postav vedle sebe dvě podoby stejné hodnoty.",
    why: "Uvidíš, že hodnotu nemusíš zahodit. Můžeš změnit způsob, jakým ji žiješ.",
    whyBullets: ["Vyber hodnotu, která je pro tebe opravdu důležitá.", "Popiš její podpůrnou i vyčerpávající podobu.", "Najdi hranici, která mezi nimi dělá rozdíl."],
    steps: ["Jak tato hodnota vypadá, když mi slouží?", "Jak vypadá, když už vytváří tlak?", "Podle jakého signálu poznám hranici?"],
    prompt: "Jak chci tuto hodnotu žít pevně a současně lidsky?",
    fields: [text("value", "Vybraná hodnota"), area("healthy", "Podpůrná podoba"), area("hard", "Tvrdá podoba"), text("signal", "Signál překročené hranice")],
  },
  {
    title: "Nastav jedné hodnotě pomyslný stmívač.",
    why: "Místo vypínače ano nebo ne prozkoumáš dávku, načasování a způsob.",
    whyBullets: ["Vyber situaci, ve které dobrá hodnota způsobila škodu.", "Ohodnoť její dnešní intenzitu od jedné do pěti.", "Navrhni o jeden stupeň pružnější podobu."],
    steps: ["Kterou hodnotu jsem použil bez ohledu na kontext?", "Na jaké intenzitě jsem ji žil?", "Jak by vypadal o jeden stupeň citlivější způsob?"],
    prompt: "Co se změní, když hodnotu nezruším, ale upravím její dávku?",
    fields: [text("value", "Hodnota v dané situaci"), scale("intensity", "Jak tvrdě jsem ji prosazoval od 1 do 5"), area("impact", "Dopad na mě a druhé"), area("softer", "Podoba o jeden stupeň pružnější")],
  },
  {
    title: "Usaď dvě hodnoty ke stejnému stolu.",
    why: "Přestaneš hledat padoucha a necháš obě strany pojmenovat, co důležitého chrání.",
    whyBullets: ["Vyber jednu nerozhodnou chvíli.", "Napiš krátkou řeč za každou hodnotu.", "U každé přiznej dar i cenu."],
    steps: ["Co mi nabízí první hodnota a co by stálo její odmítnutí?", "Co mi nabízí druhá hodnota a co by stálo její odmítnutí?", "Která potřebuje prioritu právě teď?"],
    prompt: "Jak vypadá konflikt, když mají obě strany legitimní důvod?",
    fields: [text("valueA", "První hodnota"), area("voiceA", "Co chrání a jakou nese cenu"), text("valueB", "Druhá hodnota"), area("voiceB", "Co chrání a jakou nese cenu"), area("priority", "Priorita pro tuto chvíli")],
  },
  {
    title: "Vystav dnešní volbě poctivou účtenku.",
    why: "K prioritě přidáš cenu a konkrétní návrat k tomu, co dnes muselo ustoupit.",
    whyBullets: ["Napiš jednu jasnou větu o dnešní prioritě.", "Přiznej, co za ni zaplatíš.", "Domluv konkrétní návrat k odsunuté hodnotě."],
    steps: ["Čemu dnes dávám přednost?", "Jakou cenu tím přijímám?", "Kdy a jak se vrátím k tomu, co dnes ustoupilo?"],
    prompt: "Dokážu svoji prioritu říct bez znehodnocení druhé hodnoty?",
    fields: [area("choice", "Dnes dávám přednost… protože…"), area("price", "Cena této volby"), area("return", "Konkrétní návrat k odsunuté hodnotě")],
  },
  {
    title: "Nakresli mapu jednoho vracejícího se střetu.",
    why: "Najdeš první známý okamžik konfliktu dřív, než se znovu rozjede celý automat.",
    whyBullets: ["Vyber střet, který znáš z více situací.", "Najdi jeho typický spouštěč a obvyklý konec.", "Označ místo, kde by příště mohl vzniknout jiný krok."],
    steps: ["Co tento střet obvykle spustí?", "Jak pokračuje můj známý scénář?", "Ve které chvíli je ještě možné změnit směr?"],
    prompt: "Kde je na mapě nejčasnější místo pro vědomou volbu?",
    fields: [text("conflict", "Dvě střetávající se hodnoty"), area("trigger", "Typický začátek"), area("script", "Můj obvyklý průběh a cena"), area("choicePoint", "Nejčasnější místo pro jiný krok")],
  },
  {
    title: "Sestav galerii tří věcí, které už fungují.",
    why: "Změna nebude stát jen na opravování. Vytáhneš podmínky z okamžiků, kdy už svoji hodnotu žiješ.",
    whyBullets: ["Najdi tři malé situace z posledních dnů.", "U každé označ hodnotu viditelnou v činu.", "Vyber podmínku, kterou můžeš zopakovat."],
    steps: ["Které tři činy chci v galerii zachovat?", "Co mi v nich pomohlo jednat tímto způsobem?", "Kterou podmínku si připravím znovu?"],
    prompt: "Na čem už můžu stavět, místo abych začínal od nuly?",
    fields: [area("moments", "Tři malé důkazy"), text("sharedValue", "Společná hodnota"), area("conditions", "Co mi pomohlo"), area("repeat", "Co chci vědomě zopakovat")],
  },
  {
    title: "Odděl jádro hodnoty od starého obalu.",
    why: "Ponecháš si to důležité a vyměníš pravidlo, které tě při jeho dokazování vyčerpává.",
    whyBullets: ["Pojmenuj hodnotu, o kterou nechceš přijít.", "Zachyť tvrdé pravidlo, kterým ji dnes dokazuješ.", "Vymysli dvě svobodnější podoby stejného jádra."],
    steps: ["Co chci skutečně zachovat?", "Který způsob už nechci dál dokazovat?", "Jakými dvěma jinými kroky lze žít stejnou hodnotu?"],
    prompt: "Co může zůstat, i když staré pravidlo pustím?",
    fields: [text("core", "Jádro, které chci zachovat"), area("shell", "Pravidlo, které chci pustit"), area("options", "Dvě svobodnější podoby")],
  },
  {
    title: "Udělej test prázdného hlediště.",
    why: "Na chvíli odebereš pochvalu, hodnocení a publikum a poslechneš si vlastní důvod.",
    whyBullets: ["Vyber cíl, kterému teď dáváš hodně energie.", "Představ si, že se o výsledku nikdo nedozví.", "Sleduj, která část smyslu zůstane a která zmizí."],
    steps: ["Co bych udělal, kdyby o tom nikdo nevěděl?", "Co bych bez uznání změnil?", "Který důvod je skutečně můj?"],
    prompt: "Co zůstane důležité, když zmizí potlesk?",
    fields: [area("goal", "Cíl nebo rozhodnutí"), area("withoutAudience", "Co bych udělal bez publika"), area("change", "Co bych změnil"), text("ownReason", "Můj vlastní důvod")],
  },
  {
    title: "Proměň jednu hodnotu ve tři slovesa.",
    why: "Velké slovo dostane několik konkrétních podob, ze kterých lze jednu opravdu vyzkoušet.",
    whyBullets: ["Vyber jednu zvolenou hodnotu.", "Napiš tři činnosti, které ji mohou vyjádřit.", "Jednu spoj s přesnou situací zítřka."],
    steps: ["Která tři slovesa tuto hodnotu vyjadřují?", "Které z nich je zítra nejvíc potřeba?", "Kdy a kde bude tento čin vidět?"],
    prompt: "Jak se moje hodnota přestane schovávat za abstraktní slovo?",
    fields: [text("value", "Moje hodnota"), area("verbs", "Tři slovesa"), text("chosenVerb", "Sloveso pro zítřek"), area("scene", "Konkrétní situace, čas a místo")],
  },
  {
    title: "Vystav si účtenku za jeden malý důkaz.",
    why: "Zachytíš skutečný čin, jeho účinek a přesnou úpravu dalšího pokusu.",
    whyBullets: ["Vyber čin tak malý, že se opravdu stal.", "Popiš dopad bez známky dobře nebo špatně.", "Rozhodni, co příště zopakuješ nebo upravíš."],
    steps: ["Jaký konkrétní čin se stal?", "Co přinesl mně a co druhým?", "Co z něj beru do dalšího pokusu?"],
    prompt: "Co dnes představuje malý, ale skutečný důkaz mého směru?",
    fields: [area("act", "Konkrétní čin"), area("effect", "Skutečný dopad"), area("next", "Co zopakuju nebo upravím")],
  },
  {
    title: "Navrhni sedmidenní laboratoř jedné hodnoty.",
    why: "Místo slibu vytvoříš malý experiment s jasnou situací, chováním a pozorováním.",
    whyBullets: ["Vyber jednu hodnotu a jeden typ běžné situace.", "Zvol chování, které lze vidět nebo slyšet.", "Po každém pokusu zapiš krátká data, ne známku."],
    steps: ["Ve kterých třech situacích experiment proběhne?", "Jaký jeden čin budu opakovat?", "Čeho si po každém pokusu všimnu?"],
    prompt: "Jak bude vypadat můj bezpečný sedmidenní experiment?",
    fields: [text("value", "Testovaná hodnota"), area("situations", "Tři konkrétní situace"), area("behavior", "Jeden pozorovatelný čin"), area("observe", "Co budu sledovat"), area("adjust", "Kdy experiment zmenším nebo upravím")],
  },
  {
    title: "Zedituj manifest jako dobrou pracovní dohodu.",
    why: "Odstraníš plakátová slova a necháš jen směr, činy, konflikt a způsob návratu.",
    whyBullets: ["Vyškrtni „vždy“, „nikdy“ a věty bez konkrétního jednání.", "U každé hodnoty doplň jeden běžný projev.", "Přidej větu pro chvíli, kdy se od směru odchýlíš."],
    steps: ["Které tři směry chci chránit?", "Jak budou vidět v běžném týdnu?", "Jak se vrátím po chybě bez trestání sebe?"],
    prompt: "Jak zní dohoda, která mě vede, ale nesvazuje?",
    fields: [area("directions", "Moje tři zvolené směry"), area("behaviors", "Jak budou vidět v praxi"), area("conflict", "Jak chci rozhodovat při střetu"), area("return", "Moje věta pro návrat po odchýlení"), area("manifest", "Krátká finální dohoda se sebou")],
  },
];
